import { NodeCG } from './util/nodecg';
import { countdown } from './countdown';
import { donationsPrizes } from './donations-prizes';
import { featuredChannels } from './featured';
import { footpedal } from './footpedal';
import { highligher } from './highlighter';
import { hostCountdown } from './host-countdown';
import { layouts } from './layouts';
import { milestones } from './milestones';
import { nowPlaying } from './nowplaying';
import { obs } from './obs';
import { secondaryTimer } from './secondary-timer';
import { streamDeck } from './sd';
import { total } from './total';
import { timestamps } from './timestamps';

export default (nodecg: NodeCG) => {
  countdown(nodecg);
  donationsPrizes(nodecg);
  featuredChannels(nodecg);
  footpedal(nodecg);
  highligher(nodecg);
  hostCountdown(nodecg);
  layouts(nodecg);
  milestones(nodecg);
  nowPlaying(nodecg);
  obs(nodecg);
  secondaryTimer(nodecg);
  streamDeck(nodecg);
  total(nodecg);
  timestamps(nodecg);
};
