/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Configschema {
    donationSocketUrl?: string;
    /**
     * Login information for the private areas of the tracker API.
     */
    tracker: {
        username: string;
        password: string;
        [k: string]: unknown;
    } | null;
    nowPlayingFile: string;
    /**
     * Info needed to use OBS websockets.
     */
    obs: {
        enabled: boolean;
        address: string;
        password: string;
        [k: string]: unknown;
    };
    /**
     * Info needed to control foobar2000.
     */
    foobar: {
        enabled: boolean;
        address: string;
        [k: string]: unknown;
    };
}
