/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Configschema {
  google: {
    enabled: boolean;
    spreadsheetId: string;
    service_email: string;
    private_key: string;
    [k: string]: unknown;
  };
  /**
   * Info needed to use OBS websockets.
   */
  obs: {
    enabled: boolean;
    address: string;
    password: string;
    scenes: {
      intermission: string;
      video: string;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * Info needed to control foobar2000.
   */
  foobar: {
    enabled: boolean;
    address: string;
    unmuteKeyword: string;
    [k: string]: unknown;
  };
  footpedal: {
    enabled: boolean;
    [k: string]: unknown;
  };
  twitchExt: {
    enabled: boolean;
    token: string;
    [k: string]: unknown;
  };
}
