/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Configschema {
  donationSocket: {
    enabled: boolean;
    url?: string;
    [k: string]: unknown;
  };
  milestones: {
    enabled: boolean;
    url?: string;
    [k: string]: unknown;
  };
  /**
   * Login information for the private areas of the tracker API.
   */
  tracker: {
    enabled: boolean;
    username?: string;
    password?: string;
    eventID?: number;
    rootURL: string;
    [k: string]: unknown;
  };
  google: {
    enabled: boolean;
    spreadsheetId?: string;
    service_email?: string;
    private_key?: string;
    [k: string]: unknown;
  };
  /**
   * Info needed to use OBS websockets.
   */
  obs: {
    enabled: boolean;
    address?: string;
    password?: string;
    scenes?: {
      intermission: string;
      video: string;
      hosterka: string;
      [k: string]: unknown;
    };
    croppers?: {
      url: string;
      name: string;
      sceneName: string;
      sourceName: string;
    }[];
    timestamps?: {
      enabled: boolean;
      /**
       * The path to save CSV files with VoD timestamps.
       */
      csv_folder_path?: string;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * Info needed to control foobar2000.
   */
  foobar: {
    enabled: boolean;
    address?: string;
    unmuteKeyword?: string;
    [k: string]: unknown;
  };
  footpedal: {
    enabled: boolean;
    [k: string]: unknown;
  };
  twitchExt: {
    enabled: boolean;
    token?: string;
    [k: string]: unknown;
  };
}
