/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ObsData {
  connected: boolean;
  scene?: string;
  studioMode?: boolean;
  transitioning: boolean;
  streaming: boolean;
  recording: boolean;
  recordingName: string;
  disableTransitioning: boolean;
  transitionTimestamp: number;
  croppers: {
    url: string;
    name: string;
    sceneName: string;
    sourceName: string;
  }[];
}
