# Based on the GitHub action found in the ESA layouts repo, big thanks for that

name: Build

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout NodeCG
    - name: Checkout nodecg/nodecg
      uses: actions/checkout@v2
      with:
        token: ${{ secrets['GITHUB_TOKEN'] }}
        repository: nodecg/nodecg
        ref: 'v1.8.1'
        path: ./nodecg-temp

    # Copies checked out NodeCG into permanent folder.
    # If I didn't do this, some bundles seemed to not actually checkout successfully later
    - name: Copy ./nodecg-temp > ./nodecg
      run: cp -r ./nodecg-temp ./nodecg

    # Checkout nodecg-speedcontrol, needed for types
    - name: Checkout speedcontrol/nodecg-speedcontrol
      uses: actions/checkout@v2
      with:
        token: ${{ secrets['GITHUB_TOKEN'] }}
        repository: speedcontrol/nodecg-speedcontrol
        ref: 'v2.4.0'
        path: ./nodecg/bundles/nodecg-speedcontrol

    # Checkout the main branch of this repository with full depth
    - name: Checkout this repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets['GITHUB_TOKEN'] }}
        ref: main
        fetch-depth: 0
        path: ./nodecg/bundles/gsps-layouts

    # Set the local git user config to use the GitHub Actions bot account
    - name: Set local git config user details
      working-directory: ./nodecg/bundles/gsps-layouts
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    # Recheckout both the main and build branches.
    # This can "fail" if the build branch doesn't exist, but we should continue anyway.
    - name: (Re)checkout both branches
      id: checkout
      continue-on-error: true
      working-directory: ./nodecg/bundles/gsps-layouts
      run: |
        git checkout main
        git checkout build

    # Attempt to start to merge the main branch into build.
    # This can "error" but we want to continue regardless.
    # Will only run if the checkout step was successful.
    - name: Merge main into build (1)
      if: ${{ steps.checkout.outcome == 'success' }}
      continue-on-error: true
      working-directory: ./nodecg/bundles/gsps-layouts
      run: |
        git merge --no-commit main
        git commit -m "Merge branch 'main' into build"
        

    # Setup some Node stuff
    - name: Node.js setup
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    # Set NPM cache options
    - name: Set NPM cache
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # Install NPM dependencies
    - name: Install NPM dependencies
      working-directory: ./nodecg/bundles/gsps-layouts
      run: npm ci

    # Actually build everything
    - name: Build
      working-directory: ./nodecg/bundles/gsps-layouts
      run: |
        npm run clean
        npm run build

    # Start committing newly built files into a temporary commit.
    - name: Commit built files (1)
      working-directory: ./nodecg/bundles/gsps-layouts
      run: |
        git add -f dashboard graphics extension
        git commit -m "Built files" -a --allow-empty

    # Squash the previous 2 commits down for convenience and create the final build commit.
    # Will only run if the checkout step was successful.
    # This can "fail" if there are no newly changed/built files, but we should continue anyway.
    - name: Commit built files (2)
      continue-on-error: true
      if: ${{ steps.checkout.outcome == 'success' }}
      working-directory: ./nodecg/bundles/gsps-layouts
      run: |
        git reset --soft HEAD~2
        git commit -m "Built files" -a

    # Pushes the built files to a specific branch
    - name: Push built files to "build" branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets['GITHUB_TOKEN'] }}
        branch: build
        directory: ./nodecg/bundles/gsps-layouts